version: '3.8'
services:
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - ./data/redis-data:/data
  db:
    build: ./postgis-pgvector
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db_name
    ports:
      - 5432:5432
    volumes:
      - ./data/db-data:/var/lib/postgresql/data
